import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { Inter } from '@next/font/google'
import  '../styles/Home.module.css'
import Header from '../components/layout/Header'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session, status } = useSession()

  if (status === "authenticated") {
    console.log(session)
    return <p>Signed in as {session.user.email}</p>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Homepage</title>
  <link rel="stylesheet" type="text/css" href="styles.css"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"></link>
      </Head>
     
<main>
  <Header/>
    
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Welcome to my Website</h1>
        <p class="lead">This is the home page of my website. Feel free to browse around and learn more about us.</p>
        <a href="#" class="btn btn-primary btn-lg">Learn more</a>
      </div>
    </div>
  </div>
  </main>
    </>
  )
}
