import Head from 'next/head'
import styles from '../styles/Login.module.css'
import {useRouter} from 'next/router'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Login() {
    const router =useRouter()
    const { data: session } = useSession()
    const loginHandler = (e)=>{
        e.preventDefault();
        router.push('/')


    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <form id={styles.login} action="/login" method="post">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username"/>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password"/><br/>
      <input type="submit" onClick={loginHandler} value="Login"></input>
      </form>
      </main>
    </>
  )
}
